### ISSUE TITLE
support special dub dependency version syntax

### ISSUE THREAD

**Issue by WebFreak001** [pflannery/vscode-versionlens#5]
dependency versions can also be specified with

```json
"dependencies": {
  "<dependency name>": {
    "version": "<version"
  }
}
```

I'm gonna make a PR for this later today

**Comment by WebFreak001** [comment]
But im going to wait for https://github.com/pflannery/vscode-versionlens/pull/4 to be merged as there seem to be major changes

**Comment by pflannery** [comment]
@WebFreak001 

Not sure if this is what you meant but PR #4 added the ability to read and write to a child version property. 

```js
 // codelens appears here
  "<dependency name>": {
    "version": "<version" // and text gets amended here
  }
```

should also be working for dub.

**Comment by WebFreak001** [comment]
I would try it but you didnt run `vsce publish` yet or their servers are slow <.<

**Comment by pflannery** [comment]
The dub provider is pretty much the same. 

The changes to dub provider
- I moved the selector info in to the class https://github.com/pflannery/vscode-versionlens/blob/master/src/providers/dubCodeLensProvider.js#L23-L29
- typescript fixed an issue with decorators when compile js files so injection is now using decorators.

**Comment by pflannery** [comment]
@WebFreak001 ah ok. I thought you were pulling the latest locally. 
From testing with a dub file I see it working. I will `vsce publish` this week.

**Comment by WebFreak001** [comment]
You are right, it already works in 0.4.0

**Comment by pflannery** [comment]
:+1:
